# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  database: <%= ENV["PGDATABASE"] %>

development:
  <<: *default
  database: gym_fitness_api_development

test:
  <<: *default
  database: gym_fitness_api_test

production:
  <<: *default
  # The database name, username, and password will be sourced from environment variables.
