# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  database: <%= ENV["PGDATABASE"] %>

development:
  <<: *default
  database: gym_fitness_api_development
  host: localhost
  username: <%= ENV["DEV_PGUSER"] || "your_local_user" %>
  password: <%= ENV["DEV_PGPASSWORD"] || "your_local_password" %>

test:
  <<: *default
  database: gym_fitness_api_test
  host: localhost
  username: <%= ENV["TEST_PGUSER"] || "your_local_user" %>
  password: <%= ENV["TEST_PGPASSWORD"] || "your_local_password" %>

production:
  <<: *default
  database: <%= ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
